import type { Product } from '@/types/product.types';

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Bộ Tam Sự Đồng Đỏ Cạo Màu',
    slug: 'bo-tam-su-dong-do-cao-mau',
    categoryId: '1',
    categoryName: 'Đỉnh Đồng',
    price: 15500000,
    salePrice: 14500000,
    shortDescription: 'Bộ tam sự đúc thủ công từ đồng đỏ nguyên bản, nghệ thuật cạo màu đỉnh cao mang lại vẻ đẹp cổ kính.',
    description: 'Chi tiết sản phẩm bộ tam sự đồng đỏ...',
    images: ['/images/user-images/2838860600152237389.jpg'],
    material: 'Đồng đỏ',
    color: 'Màu mộc',
    size: 'Cao 60cm',
    weight: '15kg',
    stock: 5,
    featured: true, published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Lư Hương Đồng Thau Chạm Khắc',
    slug: 'lu-huong-dong-thau-cham-khac',
    categoryId: '2',
    categoryName: 'Lư Hương',
    price: 8500000,
    shortDescription: 'Lư hương đồng thau nguyên khối, chạm khắc tinh xảo từng đường nét.',
    description: 'Lư hương đồng thau...',
    images: ['/images/user-images/3817029346785325731.jpg'],
    material: 'Đồng thau',
    color: 'Vàng mộc',
    size: 'Đường kính 30cm',
    weight: '5kg',
    stock: 10,
    featured: true, published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Bộ Ngũ Sự Đồng Cát Tút',
    slug: 'bo-ngu-su-dong-cat-tut',
    categoryId: '3',
    categoryName: 'Ngũ Sự',
    price: 25000000,
    salePrice: 23500000,
    shortDescription: 'Bộ ngũ sự đúc từ vỏ đạn cát tút quân sự, độ bền vĩnh cửu.',
    description: 'Bộ ngũ sự...',
    images: ['/images/user-images/4610757469811033814.jpg'],
    material: 'Đồng cát tút',
    color: 'Vàng ánh xanh',
    size: 'Cao 65cm',
    weight: '30kg',
    stock: 2,
    featured: true, published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Đại Tự Câu Đối Bằng Đồng',
    slug: 'dai-tu-cau-doi-bang-dong',
    categoryId: '4',
    categoryName: 'Đồ Phong Thủy',
    price: 12000000,
    shortDescription: 'Bộ đại tự câu đối chữ Hán Nôm thư pháp, thúc nổi thủ công.',
    description: 'Đại tự câu đối...',
    images: ['/images/user-images/image1.jpg'],
    material: 'Đồng vàng mỏng',
    color: 'Vàng bóng',
    size: 'Dài 1m97',
    weight: '12kg',
    stock: 0, // Hết hàng thử nghiệm
    featured: true, published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
] as Product[];

export const MOCK_CATEGORIES = [
  { id: '1', name: 'Đỉnh Đồng', slug: 'dinh-dong', image: '/images/product-1.jpg', productCount: 15 },
  { id: '2', name: 'Lư Hương', slug: 'lu-huong', image: '/images/product-1.jpg', productCount: 8 },
  { id: '3', name: 'Bộ Tam Sự', slug: 'bo-tam-su', image: '/images/product-1.jpg', productCount: 12 },
  { id: '4', name: 'Đồ Phong Thủy', slug: 'do-phong-thuy', image: '/images/product-2.jpg', productCount: 20 },
  { id: '5', name: 'Quà Tặng', slug: 'qua-tang', image: '/images/product-3.jpg', productCount: 30 },
];
